[project]
name = "lemat-rho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ase>=3.25.0",
    "ipykernel>=6.29.5",
    "material-hasher",
    "atomate2",
    "fireworks",
    "torch>=2.0",
    "numpy>=1.24",
    "e3nn>=0.5.0",
    "scipy>=1.10.0",
    "lz4>=4.0.0",
    "pyarrow>=14.0.0",
    "wandb>=0.16.0",
    "python-dotenv>=1.0.0",
    "metatensor>=0.2.0",
    "chemfiles>=0.10.4",
    "graph2mat>=0.0.13",
]

[tool.uv.sources]
material-hasher = { git = "https://github.com/LeMaterial/lematerial-hasher" }
